spring:
  application:
    name: vinylMgt
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./target/vinylDB
#logging:
#  level:
#    org.springframework: DEBUG

springdoc:
  api-docs:
    enabled: true


application:
  jwt:
    base64-secret: ZTlkOWNiMWU1ZjA1OTgwNDNkNWQwZDE0ZjgyMTFmMTY0ZTc5NDk4OTQxZjdmODlhNTMyODllYjEwNTAxMDYwZjBkZWY4ZGY1YTAxNDg5YTYxYzY0NWQ0ZGVjYzJmNTM2NGI0M2ZmMGU3NjA2MDBiMGMzMDU0ZTY4NWIzMTNjNzA
  cors:
    allowed-origins: http://localhost:4200
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "*"
    allow-credentials: false
    max-age: 300
